name: buildtool
version: 0.0.2
author: Dart Team <misc@dartlang.org>
description: A simple build system for Dart.
homepage: https://github.com/dart-lang/buildtool
dependencies:
  args: any
  http: any
  logging: any
  route: any
  unittest: any
  #TODO: make dwc depend on buildtool
  web_ui: any
    #git: git://github.com/dart-lang/web-ui.git
